apiVersion: v1
kind: Deployment
metadata:
  name: vintor-api
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: vintor-api
  template: 
    metadata:
      labels:
        app: vintor-api
    spec:
      containers:
      - name: api
        image: vladakawallet/vintor-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://localhost:6379"
        resources: 
          requests:
            memory: "2Gi"
            cpu: "1"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: 1
      volumeMounts:
      - name: models-volume
        mountPath: /models
    volumes:
    - name: models-volume
      persistentVolumeClaim:
        claimName: models-pvc 
---
apiVersion: v1
kind: Service
metadata: 
  name: vintor-Service
spec: 
  selector:
    app: vintor-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer